### ISSUE TITLE
3회 7,8

### ISSUE THREAD

**Issue by kyla333** [seoulrain/studyhacks#100]
Note that set-aside land is more permanent than fallow land, which is usually left for only a year. Colonisation is a slow process, taking place over years or even decades. 에서 Colonisation이 몇년 혹은 수십년 동안 처럼 오래 일어나는 과정이라고 굳이 언급을 한 이유가 농부들에게 (fallow land를 만드는 것 보다) 더 이익이 되어서 추가한 것 아닌가요? 만약 맞다면 왜 slow process인것이 농부들에게 이익이 되는 건가요?

**Comment by seoulrain** [comment]
음.. 본문에 그것이 더 이익이라는 이야기가 없어요. 마침 재배하지 않는 게 경제적으로도 좋으면 시도할 수 있는데, 단기간으로는 colonisation 효과가 없다는 것이죠. 

.. when that is also economically desirable ..  땅을 그냥 두는 게 차라리 경제적 손해가 아니기도 한 조건이라면, 시도해라. 

근데 1년만 놀리는 걸로는 colonisation 효과 없다. 


올해 감자값이 떨어져서 감자 안 키우는 게 경제적으로 차라리 더 좋은 상황이기도 해서 생산량을 줄여야 하는 경우라면 
Colonisation  추천한다. 

근데 주의할 점은 보통 땅에 양분 없어서 1년 땅 쉬었다가 다시 감자 심는 '휴경지' 개념처럼 쉬는 거랑 다르다. 

colonisation 은 slow process 이니깐... 스스로 회복하게 천천히 기다려줘야 하는 것.
