### ISSUE TITLE
6회 1

### ISSUE THREAD

**Issue by Aninmo** [seoulrain/studyhacks#118]
밑에서 4번째 줄에 this process는 앞에 나온 '공동체 구성원끼리 유대감이 강해서 관광객이 그 지역에 오는 것을 거부한다'는 내용을 가리키는 건가요?

위의 내용이 맞다면 이 내용 자체를 '과정'이라고 표현할 수 없는 것 아닌가요?

**Comment by seoulrain** [comment]
주의사항 다시 읽고 질문.
