### ISSUE TITLE
6회 2

### ISSUE THREAD

**Issue by Aninmo** [seoulrain/studyhacks#119]
1. Tall Poppy Syndrome 자체(오스트리안들이 이 생각을 갖고 있다는 것 자체)가 culturally prescribed behavior에 해당한다고 봐도 되는 건가요?

2. 맨 첫 문장에 self-efficacy가 '행동간의 관계를 조정하는 개인의 특성'이라고 했는데, 이 말이 왜 나왔는지 모르겠어요.

**Comment by seoulrain** [comment]
주의사항 다시 읽고 질문.
