### ISSUE TITLE
802

### ISSUE THREAD

**Issue by yejinshin01** [seoulrain/studyhacks#120]
맨 앞 줄 duty to perform an action that advances the interests of another, to the harm of one's own 이랑 prudence는 완전 똑같은 개념은 아닌건가요? 처음에 읽었을 때는 둘다 다른 사람이 어떻게 행동하느냐에 관계없이 자신의 행동이랑만 상관있는거니까 비슷하다고 생각했는데 이 점에서 비슷한 것은 맞지만, duty to perform~얘는 자기가 선행을 함으로써 희생하고 남들한테 도움을 주는 거지만 prudence는 자신이 혼자 바른생활 하는거지 그게 꼭 다른 사람한테 도움이 되려고 하는 것은 아닐 수도 있지않나요? 필자는 prudence 즉 사리 분별이라는 의미 속에서도 자신이 조금 조심해서 행동해서 다른 사람한테 피해가 안 가는 그런 prudence를 말하려고 쓴 것 같은데 '자기가 미세먼지 마스크 쓰는 것' 이 예를 생각하니까 조금 헷갈려요. 이 얘가 prudence는 맞지만 이타심을 뜻하는 것은 아니잖아요. 아니면 '남한테 미세먼지 조심하라고 미세먼지 마스크 주는 것 ' 이걸로 바꿔 생각하면 될까요?

**Comment by yejinshin01** [comment]
다른 질문 답변 읽어보니까 prudence는 자기가 잘 지켜서 자기한테 이익이 오는 행동이라고 하셨네요... 그럼 위에서 제가 물어본 둘은 같은 것은 아닌거군요. 근데 둘 다 다른 사람이 어떻게 행동하느냐에 관계없이 자신의 행동이랑만 상관있다는 점에선 유사하다고 볼 수 있나요?

**Comment by seoulrain** [comment]
> 맨 앞 줄 duty to perform an action that advances the interests of another, to the harm of one's own 이랑 prudence는 완전 똑같은 개념은 아닌건가요? 
-- 다르지요. 행위자와 수혜자의 관점에서 구분해보세요. 

>  duty to perform~얘는 자기가 선행을 함으로써 희생하고 남들한테 도움을 주는 거지만 prudence는 자신이 혼자 바른생활 하는거지 그게 꼭 다른 사람한테 도움이 되려고 하는 것은 아닐 수도 있지않나요?
-- 그렇습니다.
-- prudent 한 건 바르다/그르다 의 개념 없이 주의깊음을 통한 이익 추구인 거죠. 맞다,틀리다 .. 사리분별...서투르다.. 그런 대조라고 생각해봅시다. 


>  '자기가 미세먼지 마스크 쓰는 것' 이 예를 생각하니까 조금 헷갈려요. 이 얘가 prudence는 맞지만 이타심을 뜻하는 것은 아니잖아요. 
-- 그렇지요. prudence는 타인과의 상호호혜성이나, 남을 이롭게 하는가 해롭게 하는가와 무관함. 

>  아니면 '남한테 미세먼지 조심하라고 미세먼지 마스크 주는 것 ' 이걸로 바꿔 생각하면 될까요?
-- ... 이런 거까지 생각하면 복잡해지니까 패스

**Comment by seoulrain** [comment]
> 다른 질문 답변 읽어보니까 prudence는 자기가 잘 지켜서 자기한테 이익이 오는 행동이라고 하셨네요... 그럼 위에서 제가 물어본 둘은 같은 것은 아닌거군요. 근데 둘 다 다른 사람이 어떻게 행동하느냐에 관계없이 자신의 행동이랑만 상관있다는 점에선 유사하다고 볼 수 있나요?

-- 그렇죠. 둘 다 일단 처음 행위는 나인 거죠.
