### ISSUE TITLE
01회 2018 6월 (art/culture)

### ISSUE THREAD

**Issue by sylviapark66** [seoulrain/studyhacks#127]
According to many sociologists... we drop `the highly specific` and `ideologically loaded` terminology of 'art'....

여기서
"highly specific"를 지칭하는 부분은 본문에서 여기인가요?
these cultural products... should be regarded as being made by `certain `types of cultural producer, and as being used by `particular` groups of people in `particular` ways in `specific `social contexts.
이걸 바탕으로 highly specific 이라고 수식한 것인가요?

또한 "ideologically loaded"는
Since it is in the `interests `of certain social groups to define some things as art and others as not.
이러하느 부분이 나오기에 ideologically loaded라고 하는 것인가요?
즉 ideologically loaded(이념으로 가득찬) = 특정 이념(이익)에 영향 받은

감사합니다!

**Comment by seoulrain** [comment]
-- 저자가 cultural products 에 대한 설명에서 그것이 certain types of cultral ... 을 말한다고 설명했는데, 다시 그걸 버리자고drop 말할 수 없습니다. art 가 왜 너무나 specific 한 범주에 해당하는 용어인지를 말하는 부분을 찾아야 합니다.  본문에서 모든 사람들을 포괄하기에 부적당하다고 말하는 부분을 찾아보세요.

-- 이념적이라는 말은 특정한 의미가 짙게 들어있어서 편하게 사용할 수 없다는 뜻이에요. 빨갱이라고 하면 보통 아 빨간 사람인가? 하고 들리지 않고 뭔가 경멸하는 의미처럼 들리지요? 아트도 그냥 예술이라고 안 들리고~ 뭐가 고급진 것이라든가 미술관이 생각난다든가.. 이렇게 나이브하게 사용하기 힘든 용어라는 것이죠. 

--

**Comment by sylviapark66** [comment]
선생님 그러니까요 본문에서
(Art) is a category that is too **limited and context-specific** to encompass all the different cultural products that people in different societies make and use 이라고 나와있어서 

그 위에 나온
should be regarded as being made by **certain** types of cultural producer, and as being used by **particular** groups of people in **particular** ways in **specific** social contexts
이 단어들에 집중한 거에요

그러니까 예술이 이렇게 certain, particular, specific한 것들을 하나로 퉁치니까 이것도 비슷한 맥락이 아닌가 싶었어요.

limited and context-specific이 곧 highly-specific과 같을 텐데요 그 근거는 도데체 어디서 찾아야 될까요? 다시 봐도 잘 모르겠네요;;

제가 이해하기론:
highly specific>> because usually most art is made by **certain** types of cultural producers in **particular** ways in **specific** contexts >> therefore we mustn't use the term "art" that is influenced by these specific contexts but use the term "cultural forms" .

**Comment by sylviapark66** [comment]
그리고 

> ideologically loaded(이념으로 가득찬) = 특정 이념(이익)에 영향 받은 


으로 이해하면 안되겠네요?

**Comment by seoulrain** [comment]
> 선생님 그러니까요 본문에서
> (Art) is a category that is too **limited and context-specific** to encompass all the different cultural products that people in different societies make and use 이라고 나와있어서
> 그 위에 나온
> should be regarded as being made by **certain** types of cultural producer, and as being used by **particular** groups of people in **particular** ways in **specific** social contexts
> 이 단어들에 집중한 거에요
> 그러니까 예술이 이렇게 certain, particular, specific한 것들을 하나로 퉁치니까 이것도 비슷한 맥락이 아닌가 싶었어요.
> limited and context-specific이 곧 highly-specific과 같을 텐데요 그 근거는 도데체 어디서 찾아야 될까요? 다시 봐도 잘 모르겠네요;;

-- 저자는 'cultural producs'를 'art' 대신 사용하자고 말합니다. 
-- 문화적 산물products 이라는 것은 특정한 맥락에서 특정한 방식으로 특정한 그룹이 만들어내고 특정한 제작자가 결국 만들어낸 결과물이지요. cultural products should be regarded as being made by certain types of cultural producer and used by particular groups of people in particular ways in specific social contexts.. 
-- 저자는 이러한 cultural products 라는 개념이 중립적neutral 하다고 생각하지요. 방금전에 특정하다고 했는데 왜 중립적인가? .. 중립적입니다. 왜냐하면 all the diffrent cultural products 가 있기 때문이지요. 
-- art는 모든 문화적 산물을 포괄하지 못하고 .. 어떤 맥락만 context-specific  가리킵니다. 글을 문장 단위로 이어서 읽으면서 논의를 어떻게 이끌고 가는지 잘 보세요. cultrural products 는 모두 특정 맥락에 있다고 생각해야 한다 = 이게 예술의 특정적 성격을 가리키는 부분이라고 읽으면 완전 반대로 읽고 있는 것입니다. 

(예)
- 한국 예술품, 한국 예술가 이런 말 쓰지 말자. 
- 이런 말 대신에 더 중립적인 단어 쓰자. 한국 문화에서 나온 산물이다. 한국의 문화를 표현하는 제작자이다.. 그런 말이 더 좋다. 
- 문화라는 말이 더 중립적이다. 모든 모든 한국의 문화적 산물이라고 하면 그 모든 것이 어떤 사람이 어떤 이유로 어떤 맥락에서 구체적인 이유를 가지고 만들었다고 생각해야 한다. (특정한 맥락에서 다 사회적 contexts에서 만들어지는 건데 왜 예술은 그런 걸 편 가르나?)
- 특정한 뭘 만들었는데 한국 예술품이다라고 부르는 대신 한국의 문화적 산물이다 이렇게 부르면 .. 좋은데 .. 예술은 너무 가리키는 범위가 좁고 제한적이고 .. 맥락에 한정된context specific 용어이다. (어떤 맥락이 아니면 예술이 아니라고 한다). 그래서 모든 문화적 산물을 예술이라는 말로 포함할 수가 없다. 
- 더 넓고, 좁은 맥락에 국한되지 않은, 특별히 어떤 사회 집단에게 유리하게 이념 편향적이지도 않은 '문화적 산물'이라는 말 씁시다.

**Comment by seoulrain** [comment]
> 그리고
> 
> > ideologically loaded(이념으로 가득찬) = 특정 이념(이익)에 영향 받은
> 
> 으로 이해하면 안되겠네요?

이념이 많이 들어가있다 = 중립적이지 않다

**Comment by PurpyThePolite** [comment]
선생님 저도 이거 헷갈려서 질문하려고 했는데 똑같은 얘기 하고 있어서 좀 끼어들게요.. 

**" art "**
-specific 
-ideologically loaded
-too limited 
-context-specific 

그 반면..

**" cultural products "**
-neutral
-less historically specific 

=> cultural products 가 더 넓은 범주이다!

_"... these cultural products... should be regarded as being made by certain types of cultural producer, and as being used by particular groups of people in particular ways in specific social contexts."_ 

### 그 말인즉슨..
certain type 가 있으며, particular groups 의 사람들에게 specific 한 context 에서 particular 한 방법으로 이용되는 것은 _art 라는 term 의 특성이 아닌 cultural product 의 특징임._

그러니까, 이러한 particular 한 문화적 생산물들이 하나로 퉁칠 수 없게끔 다양하게 존재하니까 (=specific 하고 certain 한 각각의 context 에서 존재하니까) 우리는 그걸 다 encompass 할 수 있는 cultural products 를 써야 한다. 

로 제 나름대로 정리해봤는데, 이게 맞나요?

**Comment by seoulrain** [comment]
거참.. 내가 설명을 못하나봐.. 끝나지를 않네.. 

자꾸 혼자 말을 붙이니까 이해가 안 되는 거 같아요. 글을 글로 읽어야 합니다. 차례차례 이어지는 문장으로 읽어보세요. 

A = 아트
C = 문화적 산물


1. We should replace  A with C.   아트 버리고 C 가자. 
2. C are **particular things** produced by particular groups of people.   (C는 하나하나 다 달라)
3. We should use more neutral term  for **that particular things**.  (그렇게 서로 다른 특별한 맥락이 있는 걸 가리키는 말을 쓸 때 중립적인 말을 써야지)  = C 쓰자. 
4. 왜? A is too limited and context-specific to have all the different particular things .  (아트는 너무 좁고 세상에 그렇게 수많이 저마다의 맥락을 가지고 있는 모든 particular things를 다 포함할 수 없는 개념이야)


1. 종업을 호칭할 때 아줌마라고 부르지 말고 종업원님이라고 부릅시다. 
2. 종업원이라는 건 특정한 성별, 특정한 근무 이유, 특정한 연령대, 특정한 업종에서 근무하는 사람을 말하는 것으로 생각해야 한다. 
3. 이 특정한 사람을(저마다의 성별과 나이와 환경이 다른) .... 가리키는 용어로  특정한 성별이나 특정한 나이만을 가리키는(context-specific) 아줌마 대신에 ~~~ 모든 서로다른all the different 환경에서 일하는 다양한different 성별을 포괄encompass  할 수 있는 종업원을 씁시다. 
4. 아줌마라고 하면 너무 범위가 too limited 제한되어 있는 범위를 가리키고 ...   사회적으로도 편견이 이미 들어가있는loaded 개념이니까요. 



나.. 이제 .. 더 이상 이거 설명 안 할래..
