### ISSUE TITLE
8회 2번 (morality)

### ISSUE THREAD

**Issue by sylviapark66** [seoulrain/studyhacks#131]
첫번째 문장
Morality often expresses itself as a duty to perform an action that advances the interests of another to the harm of one's one.
을 제시한 이유는 보통 도덕성은 `내가 피해를 감수하면서 남을 도와주는 것이다`라고 생각할 순 있지만 그 다음에 나오는 "However, moral actions usually do not occur in isolation....." 등 뒤에 나오는 전체 내용을 통해 `피해는 무슨 피해? 너도 이익 받긴 받아` 하면서 부정하는 흐름인가요?

**Comment by seoulrain** [comment]
> Morality often expresses itself as a duty to perform an action that advances the interests of another to the harm of one's one.

저자는 일반적으로 생각하는 morality의 개념이 틀렸다고 말하고 있지요.
