### ISSUE TITLE
추가문제

### ISSUE THREAD

**Issue by CHIPnDALE1** [seoulrain/studyhacks#134]
503 역할이 부여하는 규칙
사회회란 무엇이고 어떤 역할을 하는가?
-> 사회화는 우리에게 역할을 부여하며 그 역할에 알맞는 행동을 하게 만든다. 사회화는 철저하기 때문에 사회화가 형성하는 제한들에 방해받지 않는 이들은 소수이다 
라는 답변이 충분한가요? 세부적인 내용이 더 필요한가요? 
702 자동성
we think in words, and we can only process words slowly 와 같이 말한 맥락을 좀 더 설명해 보자
--> 생각을 할 때 말로 생각하는데, 말은 처리할 때 오래 걸리기 때문에 생각하는 건 자동생을 방해 disrupt 하는 것 밖에 되지 않는다 라고 설명했는데 여기서 words을 그냥 '말'로 단순히 표현해도 맞는지 모르겠어요 ㅠㅠ

**Comment by CHIPnDALE1** [comment]
---보충-----
503 답변 근거 : Almost all of us follow the guidelines for what is "appropriate" for our roles. Few of us are bothered by such restrictions, for our socialization is so thorough that we usually want to do what our roles indicate is appropriate. 
--> 이건 사회화의 역할에 대한 내용이 아니라 roles의 역할에 관한 내용인데 잘못 생각했나요?
702 저 문장 앞 본문 내용: All we need to do is hold an image in our mind, and our automated motor plan will run off smoothly. But we, because we are clever and thikn we know better, don't let it. We interfere by thinking. 생각을 하는 거 자체가 우리의 자동성을 interefere 방해 하는데, 생각은 말들로 이루어지고 말들은 처리하는데에 시간이 걸리기 때문에 우리의 자동화된 skill을 손상시키는 결과를 결국 만든다 라는 맥락으로 이해했어요

**Comment by seoulrain** [comment]
> 503 역할이 부여하는 규칙
> 사회회란 무엇이고 어떤 역할을 하는가?
> -> 사회화는 우리에게 역할을 부여하며 그 역할에 알맞는 행동을 하게 만든다. 사회화는 철저하기 때문에 사회화가 형성하는 제한들에 방해받지 않는 이들은 소수이다
> 라는 답변이 충분한가요? 세부적인 내용이 더 필요한가요?
-- 본문에 근거했는지를 검토했다면 좋은 답변입니다. 


> 702 자동성
> we think in words, and we can only process words slowly 와 같이 말한 맥락을 좀 더 설명해 보자
> --> 생각을 할 때 말로 생각하는데, 말은 처리할 때 오래 걸리기 때문에 생각하는 건 자동성을 방해 disrupt 하는 것 밖에 되지 않는다 라고 설명했는데 여기서 words을 그냥 '말'로 단순히 표현해도 맞는지 모르겠어요 ㅠㅠ
-- 말=생각 으로 카테고리를 묶어 생각하는 점을 이해하는지 궁금해서 던진 질문이었습니다.

**Comment by seoulrain** [comment]
> ---보충-----
> 503 답변 근거 : Almost all of us follow the guidelines for what is "appropriate" for our roles. Few of us are bothered by such restrictions, for our socialization is so thorough that we usually want to do what our roles indicate is appropriate.
> --> 이건 사회화의 역할에 대한 내용이 아니라 roles의 역할에 관한 내용인데 잘못 생각했나요?
-- 우리의 역할에 "적절하다"고 여겨지는 바에 대한 가이드라인을 따른다고 했지요. 역할=학생 / 학생에게 적절하다, 즉 학생답다고 여겨지는 가이드라인을 따르도록 하는 것이 사회화가 되겠습니다. 




> 702 저 문장 앞 본문 내용: All we need to do is hold an image in our mind, and our automated motor plan will run off smoothly. But we, because we are clever and thikn we know better, don't let it. We interfere by thinking. 생각을 하는 거 자체가 우리의 자동성을 interefere 방해 하는데, 생각은 말들로 이루어지고 말들은 처리하는데에 시간이 걸리기 때문에 우리의 자동화된 skill을 손상시키는 결과를 결국 만든다 라는 맥락으로 이해했어요
-- Good.
