### ISSUE TITLE
1회 2번 

### ISSUE THREAD

**Issue by PurpyThePolite** [seoulrain/studyhacks#150]
“the average life of a street tree surrounded by concrete and asphalt is seven to fifteen years.” 여기서 사소하게 헷갈리는데요... 제가 해석한 대로라면 여기서 수명이 7~15년이라는 것은, 나무가 살아가는데 필요한 것 (soil, water) 가 구비되었을때 그만큼 산다는 것이죠?( 그게 구비가 안돼서 그만큼밖에 못산다는게 아니라??) 
지상에서 봤을때는 콘크리트와 아스팔트로 surrounded 되잇지만 결국에 중요한건 지하의 요소들이라는 게 맞나요?

**Comment by seoulrain** [comment]
> “the average life of a street tree surrounded by concrete and asphalt is seven to fifteen years.” 여기서 사소하게 헷갈리는데요... 제가 해석한 대로라면 여기서 수명이 7~15년이라는 것은, 나무가 살아가는데 필요한 것 (soil, water) 가 구비되었을때 그만큼 산다는 것이죠?( 그게 구비가 안돼서 그만큼밖에 못산다는게 아니라??) 지상에서 봤을때는 콘크리트와 아스팔트로 surrounded 되잇지만 결국에 중요한건 지하의 요소들이라는 게 맞나요?

△ 그 전 문장에서 hard to survive 라고 했으니, 일반적으로 지상에 작은 숨구멍?만을 허락받은 가로수들의 수명이 길지 않다는 것을 말해줍니다. 이 길지 않은 평균 수명 이상인가 이하인가에 영향을 끼치는 요소는 이제 지하에서 결정된다는 설명인 셈.
