### ISSUE TITLE
1회 4번 

### ISSUE THREAD

**Issue by PurpyThePolite** [seoulrain/studyhacks#151]
“sadly, human beings are in fact the only species that will deliberately deprive themselves of sleep without _any legitimate gain_.” legitimate gain 이 여기서 말하는게 뭔가요? 이 문장을 역으로 보면 legitimate gain 이 있을때는 인간 외에도 잠을 안자는 동물 종이 있을 수 있다는 뜻으로 읽히는데, 저는 그래서 뭐 포식자에게 쫓기는 초식동물의 상황 같은걸 생각했어요..(그러면 어쩔 수 없이 잠을 안잘 수도 있고, 이는 인간들이 일하려고 안자는거랑은 달리 생존에서 나오는 legitimate gain 이니까 ).. 굳이 저 표현이 나온 이유가 궁금해요. 제가 이해한게 맞나요??

**Comment by seoulrain** [comment]
> “sadly, human beings are in fact the only species that will deliberately deprive themselves of sleep without any legitimate gain.” legitimate gain 이 여기서 말하는게 뭔가요? 이 문장을 역으로 보면 legitimate gain 이 있을때는 인간 외에도 잠을 안자는 동물 종이 있을 수 있다는 뜻으로 읽히는데, 저는 그래서 뭐 포식자에게 쫓기는 초식동물의 상황 같은걸 생각했어요..(그러면 어쩔 수 없이 잠을 안잘 수도 있고, 이는 인간들이 일하려고 안자는거랑은 달리 생존에서 나오는 legitimate gain 이니까 ).. 굳이 저 표현이 나온 이유가 궁금해요. 제가 이해한게 맞나요??

△ 맞는 거 같아요 : ) 자연에서 가령 .. 겨울 내내 잠을 자는 곰은 에너지를 절약할 수 있다든지 어떤 이득gain이 있기 때문에 그러한 행동을 택하지 않습니까? 고래는 잠을 자지 않는다고 하는데, 좌뇌와 우뇌가 번갈아가면서 휴식을 취하고 계속 헤엄친다고. 이것은 고래가 헤엄을 멈추고 정말 자버리면 호흡에 심각한 결과를 초래할 수도 있기 때문임. 오직 인간만이 시험 공부할라고 일부러 안 자는 동물임. 생물학적으로 타당한 이득 없이 말이죠.
