### ISSUE TITLE
1회 #4

### ISSUE THREAD

**Issue by yejinshin01** [seoulrain/studyhacks#156]
Every component of wellness, and countless seams of societal fabric are being eroded by our costly state of sleep neglect: human and financial alike. So much so that the WHO has know declared a sleep loss epidemic throughout industrialized nations.
 첫번째 문장 뒤에 두번째 문장이 연결될 수 있는 이유가 앞문장이 sleep neglect이 costly 하다고 했고  '손실이 너무 커서( so much so that) 이건 그냥 (몸만 조금 힘든) 상태가 아니라 거의 질병이다.' 라는 뜻으로 연결된거에요??

**Comment by seoulrain** [comment]
네~
  

  

  
human/financial 측면의 손실이 커서   
  
wellness + seams of society's fabric   
  
이 둘 다 훼손되고 있다는 진단이 먼저 앞서 있었고,   
  

  
그 다음 문장에서 그러한 손실이 너무나 커서(so much) ... 질병 분류에 이르게 되었다고 이어서 읽으면 되겠습니다.   
  

  
  

  
  
>
