### ISSUE TITLE
문법질문 07,08

### ISSUE THREAD

**Issue by PurpyThePolite** [seoulrain/studyhacks#183]
프린트 질문입니다.

Q1.
in business settings, it's really easy to forget ( taking / to take ) the time to say thank-you. 
여기서 둘다 되는 것 같아보이는데.. 맞나요??

Q2. 
those who donate to one or two charities seek evidence about what the charity is doing and ( that) it is really having a positive impact
evidence that it is really having a positive impact < 로 이어져서 that이 들어가는건가요?

Q3. we anticipate the future as is we ( find / found / had found) it too slow in coming and we (are/were/had been) trying to hurry it up. 
이거 find/are 로 쓰면 틀리나요??

너무 질문이 간략한 것 같지만... 문법이어서 어떻게 설명을 못하겠어요
도와주에요!!

**Comment by seoulrain** [comment]
> Q1.
> in business settings, it's really easy to forget ( taking / to take ) the time to say thank-you.

-- forget taking time : 과거에 시간을 냈던 것을 까먹다
-- forget to take time : 이제 시간을 내야 하는데 까먹고 안 함. 
-- 본문에서는 참 고맙다는 말을 해야 하는데 안 하는 경우가 잦다는 뜻이므로 후자가 되어야. 


> Q2.
> those who donate to one or two charities seek evidence about what the charity is doing and ( that) it is really having a positive impact 
> ... evidence that it is really having a positive impact < 로 이어져서 that이 들어가는건가요?

-- 넵. 동격입니다. .




> Q3. we anticipate the future as if we ( find / found / had found) it too slow in coming and we (are/were/had been) trying to hurry it up.
> 이거 find/are 로 쓰면 틀리나요??

-- 안 틀립니다. 
-- We anticipate the future as if we find  ... 
이라고 쓰면 정말 그런 것처럼 기대한다는 직접적으로 대놓고 어쩌면 그런 것 같다는 뉘앙스가 강해지고요
-- We anticipate the future as if we found it slow in coming .. 라고 쓰면 실제로 미래가 느리게 오는 것도 아닌데 느리다고 생각하는 것처럼~ 이란 맥락이 강해지지요. 본문에서는 저자가 미래는 일정하게 오는 것인데 우리는 마치 더 빨리 왔으면 좋겠다며 재촉하는 듯한 (불합리한) 태도를 지니고 있다는 비판적 맥락에서 이야기하면서 .. 대체 왜들 그러는 걸까?라는 뉘앙스가 있어서 found가 더 좋을 듯.
