### ISSUE TITLE
T2-17 behavioural terms 

### ISSUE THREAD

**Issue by goodbeing1231** [seoulrain/studyhacks#204]
Desmond Morris, a British zoologist, notes in his book `Catwatching` that "the domestic cat is a contradiction!" Morris describes what he calls the animal's "double life." He feels that domestication has changed the cat very little, that "both in anatomy and behavior it is still remarkably like the African wild cat from which it was gradually developed." Biologist John Bradshaw points out that the cat "is neither a man-made species like the dog, nor simply an animal made captive for utilitarian purposes, like the elephant." He later asserts that "**in behavioural terms**, domestication has probably had less effect on the cat than on any other domestic mammal." Mildred Kirk agrees, offering the term "house cat" in favor of "domestic cat," as the latter does not accurately describe the feline's nature. So people who encounter the cat in daily life may observe that the animal is both domestic and wild, or somewhere in between. 

'in behavioural terms'가 굳이 들어가는 이유가 뭐고, 어떻게 해석해야 되요?  'asserts that domestication has ... than any on any other domestic mammal" 에서 주장의 맥락을 수식하는 걸로, 고양이가 **행동하는 것을 봤을 때** domestication의 영향을 거의 안 받았다 봐야 되요?  (domestication 의 영향을 받은 정도를 행동 외의 요소로 파악하고 비교하는게 잘 상상이 안 가서... ) 

그리고 구글에 찾아보니까 behaviourist approach 와 함께 behavioural approach 도 심리학 용어로 나오는데 위 지문의 표현을 '행동주의적 관점' 이라고 해석하는 것도 가능할까요?

**Comment by seoulrain** [comment]
> 'in behavioural terms'가 굳이 들어가는 이유가 뭐고, 어떻게 해석해야 되요? 'asserts that domestication has ... than any on any other domestic mammal" 에서 주장의 맥락을 수식하는 걸로, 고양이가 행동하는 것을 봤을 때 domestication의 영향을 거의 안 받았다 봐야 되요? (domestication 의 영향을 받은 정도를 행동 외의 요소로 파악하고 비교하는게 잘 상상이 안 가서... )

-- 해부학적으로나 행동 측면에서 사실상 아프리카 와일드캣과 유사하다는 내용이 위에 언급되었었지요. 유전적, 해부학적인 걸 떠나서 고양이 하는 짓만 보고 얘기를 했을 때 전혀 집에서 키우는 다른 동물들처럼 길들여지지 않았다는 이야기. 가령 소의 경우에 ... 적어도 행동 측면에서 봤을 때 야생의 소와 완전 다른 성격과 습성을 보이지요. 고양이는 그렇지 않다는 것. 
-- 개의 송곳니가 고기를 찢기 더 좋은 늑대보다는 인간의 밥을 얻어먹느라 덜 날카롭게 진화했다든가 .. 가축이 원래의 야생 조상과 해부학적으로나 유전적으로 다른 변화도 고려할 수 있습니다. 그거 말고 행동하는 거 보고 얘기하면... 고양이가 그렇다는 .. 

> 그리고 구글에 찾아보니까 behaviourist approach 와 함께 behavioural approach 도 심리학 용어로 나오는데 위 지문의 표현을 '행동주의적 관점' 이라고 해석하는 것도 가능할까요?
-- 행동주의자/행동주의 심리학적 접근은 자극stimulus, 강화reinforcement 등이 연관되어 있는 개념으로 지금 고양이에게 어떤 자극과 조건 반사, 강화 이야기를 하는 맥락이 아니므로 이 본문과는 무관합니다.
