### ISSUE TITLE
13강 6번 trading mortality statistics

### ISSUE THREAD

**Issue by goodbeing1231** [seoulrain/studyhacks#205]
For many years the British-French rivalry has extended from rugby matches, politics and trading insults to trading mortality statistics. Since records (statistics) in France started to be accurately collected, they have reported considerably fewer deaths from heart disease and a longer lifespan than the British. 

trade insults 가 숙어표현인 건 알지만 그냥 insults를 교환하다, 주고받는다 = 서로 insult 한다로 받아들일 수도 있다고 생각했는데, 
trading mortality statistics 이 부분에서 mortality statistics 를 주고받는다 는 어색할 것 같고, mortality statistics 까지 동원해서 서로를 깐다 
이렇게 해석하면 될까요?

**Comment by seoulrain** [comment]
-- 맥밀란 사전 : trade blows/insults
if people trade blows or insults, they hit or insult each other

-- trading statistics 는 앞의 trade insults 에 짝 맞춰서 쓴 거죠. 통계를 근거로 서로를 비난하는 자세한 이야기가 뒤에 이어지므로 통계가 비난의 수단인 셈.
