### ISSUE TITLE
2회 1번

### ISSUE THREAD

**Issue by Uniconnie01** [seoulrain/studyhacks#206]
마지막 문장: The statement remains implacably true, even though starvation also may sometimes subserve ends that are good.
에서 ends that are good 은 biological evolution을 지칭하는 건가요, 아니면 genetic variants를 지칭하는건가요? genetic variants가 어쨌든 biological evolution에 의해서 나타나는 것이니까 (유전적 다양성이 생물학적 진화에 포함되는 것이니까) 결국엔 biological evolution을 지칭하는것이라고 보는게 더 자연스러운가요?

**Comment by seoulrain** [comment]
> 마지막 문장: The statement remains implacably true, even though starvation also may sometimes subserve ends that are good.
> 에서 ends that are good 은 biological evolution을 지칭하는 건가요, 아니면 genetic variants를 지칭하는건가요? genetic variants가 어쨌든 biological evolution에 의해서 나타나는 것이니까 (유전적 다양성이 생물학적 진화에 포함되는 것이니까) 결국엔 biological evolution을 지칭하는것이라고 보는게 더 자연스러운가요?

-- starvation 이 어떤 좋은 목적을 향해 도움이 되는지는 본문에 잘 서술되어 있지요. genetic variants  = 유전적 변종 자체가 좋은 목적이라고 보기는 어려우나, 본문에 그러한 변종이 (언제나 그런 것은 아니지만) 새로운 종의 출현을 가능하게 한다는 점을 말하고 있습니다. 

-- (본문과 별도로) 유전적 변이가 늘 진화를 말하는 것은 아닙니다. 가령 다리가 세 개 달린 개구리의 돌연변이는 다시 도태되고 주류에 들어가지 못하고 사라지지요. 하지만 그런 변이들 중 소수는 생존에 유리할 수 있고 그럼 아예 새로운 종으로 가지치기할 수 있다고 하네요.
