### ISSUE TITLE
2회 2번 

### ISSUE THREAD

**Issue by Uniconnie01** [seoulrain/studyhacks#207]
도마뱀은 suction, 즉 흡착력을 거의 사용하지 않는다고 본문에 나와서.. 흡착력이 뭔지 사전적으로 찾아봤어요. '어떤 물질이 다른 물질에 달라붙는 힘'이라고 정의되는데, 도마뱀의 발에 있는 주름들과 돌기들로 인해서 결국엔 흡착력이 발생하는 것 아닌가요?.....

**Comment by seoulrain** [comment]
suction 흡착은 .. 

![f53ca9ff0](https://user-images.githubusercontent.com/5708556/60708060-20e74580-9f48-11e9-973c-6da1795298e6.jpg)

요렇게 공기 압력을 이용하는 방식으로 ... 문어 빨판 같은 거고요.


도마뱀이나 파리의 다리 같은 건


![2019-07-05 17_14_03-도마뱀 발 현미경 - Google 검색 - Chrome](https://user-images.githubusercontent.com/5708556/60708148-58ee8880-9f48-11e9-9ac6-614fcab699a9.png)


이렇게 까슬까슬한 표면이라는 거죠.
