### ISSUE TITLE
육회 7~8

### ISSUE THREAD

**Issue by soojinisawesome** [seoulrain/studyhacks#21]
I resisted the temptation to say light considers all paths and chooses the one that takes the least time. **This** is because I fully expect that my online opponent would later quote me as implying that light has consciousness. 

This가 지칭하는 게 the reason why i resisted인가요? 그리고 그 문장을 쓴 이유가 "아 말조심해야지" 이런 느낌인가요?

**Comment by seoulrain** [comment]
마지막 문장을 보면, 
빛이 의식consciousness 가 없는 건 맞는데, 수학적으로 보면 거의 그렇다고 할 수준이다.. 라고 글을 맺고 있지요. 

사실 거의 그렇게 보이는 정도가 맞고, 결과적으로 수학적으로 빛은 최단거리를 찾아 뚫고 지나가게 되는 것으로 보이지만.. 또 그렇게 말하면 빛을 생물인 것처럼 묘사했다고 오해하는 사람이 있을까봐 그렇게까지는 말하진 않겠다 ====> 사실 거의 그러한 게 맞긴 하다.. 는 뉘앙스죠. 

 I resisted the temptation to say “the end of an era”. 
세기의 종말이라고 말하고 싶은 걸 참았다. 
====> 누가 또 사이비라고 할까봐 그런 말까지는 못 꺼냈는데 
거의 비슷한 급 아닌가? 라는 말하는 사람의 생각을 표현하는 문장이죠.

**Comment by soojinisawesome** [comment]
예를 들어서 남원에 사는 사람들은 그냥 자기들끼리 소소하게 전통문화를 보존하면서 살고 싶은데 춘향전의 배경이라는 이유로 관광화되고 그
지역의 역사라든가 그런거 말고 그 소설 때문에 그냥 한복 빌려서 그네타는 인생샷 찍는 장소로 전락한 것. 그 지역이 활성화되고 외부로
알려지긴 했지만...

**Comment by soojinisawesome** [comment]
이거 댓글 잘못 달았어요. 1번 문제인데
