### ISSUE TITLE
2회 6

### ISSUE THREAD

**Issue by yejinshin01** [seoulrain/studyhacks#213]
마지막줄 It would not have taken long for mankind to apply this advantage to other goods.  에서 this advantage 는 boat라고 할 수 있잖아요
그러면 위에 a Stone Age genius realized the enormous hunting advantage he would gain by being abe to glide over the water's surface ,and build the first boat.에서 프린트 보면 this advantage= 물에 있는 순록 가까이 가는 것. 이거는 배를 만들어서 할 수 있음. 근데 정확히 이 지문에서 나오는 표현으로 찾아쓸만한건 없는거죠??

**Comment by seoulrain** [comment]
THE enormous hunting advantage 
which he would gain by being abe to glide over the water's surface ,and build the first boat

즉 the hunting advantage 는 다른 게 아니라 어떤 것이라는 설명 자체가 뒤에 달려있지요
프린트 내용은
 he would gain by being abe to glide over the water's surface ,and build the first boat
를 읽어놓은 것입니다.
