### ISSUE TITLE
이런건 왜 붙이셨어요

### ISSUE THREAD

**Issue by goodbeing1231** [seoulrain/studyhacks#217]
![20190716_163140](https://user-images.githubusercontent.com/52336862/61451167-c9a79300-a993-11e9-92ca-89c08e0dc40f.jpg)

이런건 왜 붙이셨어요

**Comment by seoulrain** [comment]
엥 등급컷 예상자료인데 정확히 무슨 질문이에요?
  
  
>

**Comment by goodbeing1231** [comment]
1) 누구를 위한 예상 등급컷 자료입니까? 

4등급 컷까지는 나와있지만 5,6,7,8,9등급 컷이 안 나와있는데, 5,6,7,8,9등급을 받을 애들은 정말 자기 성적에 관심이 없을까요? 아니면 혹시 "헐 8등급컷이 7점이야 와 못하는 애들 많다" 라고 성적 좋은 애들이 떠들고 옆에 7점 받은 애가 상처받는 일을 피하려고 표시를 안 하신 건가요? 

2) 반별 1등의 점수가 나와있는데, 반마다 분위기는 다르겠지만... 애들이 성적에 얼마나 민감하고 서로의 성적에 궁금해하는건 뻔하게 아실 거라고 생각하고... 8반에 만점자가 한 명 있어! 그러면 그게 누구인지 뻔할 수도 있고 8반 애들끼리 누구야? 누구야? 할 수도 있는데... 이걸 굳이 공개해야 될까요?? 

개인차는 있겠지만 제가 만약 전교 1등을 한 학생이었다면 소속 반까지 드러나는 이런 게시물이 상당히 불편했을 것 같습니다. 

3) 반별 평균을 공개하는게 자극이 될 수도 있지만... 어차피 영어과가 넘사벽인데 우리는 포기하자 가 될 가능성도 있을 것 같아요. 6반 애들이 기분 나빠할 수도 있을 것 같은데.. 

4) 영어과만 선택형, 서술형이 표시되지 않은건 채점이 덜 끝나서 그랬던 건가요, 아니면 특별한 이유가 있나요? 

5) 여론 

다음 날이 되자 잠잠해졌지만 화요일에 종례 끝나고 나서 다들 이걸 왜 붙이신건지 궁금해했어요. "내신 끝났는데 또 경쟁시키려는거야 뭐야" 라는 얘기도 나오고.... 


저는 개인적으로 전교생 종합/선택형/서술형 평균, 등급컷을 공개하신거,  어쩌면 영역별 전교 최고점수까지 공개됐어도 그러려니 했을 것 같은데 이렇게까지 구체적인 데이터를 공개하시는 취지를 잘 모르겠고 약간 불편합니다.

**Comment by goodbeing1231** [comment]
1) 누구를 위한 예상 등급컷 자료입니까?

4등급 컷까지는 나와있지만 5,6,7,8,9등급 컷이 안 나와있는데, 5,6,7,8,9등급을 받을 애들은 자기 성적에 관심이 없다고 누가 그럽니까? 아니면 혹시 "헐 8등급컷이 7점이야 와 못하는 애들 많다" 라고 성적 잘 받은 애들이 떠들고 옆에 7점 받은 애가 상처받는 일을 피하려고 표시를 안 하신 건가요?

2) 반별 1등의 점수가 나와있는데, 반마다 분위기는 다르겠지만... 애들이 성적에 얼마나 민감하고 서로의 성적에 궁금해하는건 뻔하게 아실 거라고 생각하는데... 8반에 만점자가 한 명 있어! 그러면 그게 누구인지 뻔할 수도 있고 8반 애들끼리 누구야? 누구야? 할 수도 있는데... 이걸 굳이 공개해야 될까요??

개인차는 있겠지만 제가 만약 전교 1등을 한 학생이었다면 소속 반까지 드러나는 이런 게시물이 상당히 불편했을 것 같습니다.

3) 반별 평균을 공개하는게 자극이 될 수도 있지만... 어차피 영어과가 넘사벽인데 우리는 포기하자 가 될 가능성도 있을 것 같아요. 6반 애들이 기분 나빠할 수도 있을 것 같은데..

4) 영어과만 선택형, 서술형이 표시되지 않은건 채점이 덜 끝나서 그랬던 건가요, 아니면 특별한 이유가 있나요?

5) 다음 날이 되자 잠잠해졌지만 화요일에 종례 끝나고 나서 다들 이걸 왜 붙이신건지 궁금해했어요. "내신 끝났는데 또 경쟁시키려는거야 뭐야" 라는 얘기도 나오고....

저는 개인적으로 전교생 종합/선택형/서술형 평균, 등급컷을 공개하신거, 어쩌면 영역별 전교 최고점수까지 공개됐어도 그러려니 했을 것 같은데 이렇게까지 구체적인 데이터를 공개하시는 취지를 잘 모르겠고 약간 불편합니다.

**Comment by seoulrain** [comment]
일단 그냥 넘어가지 않고 질문 올려줘서 고마워요. 
사실 붙이고 나서 반응이 좋지 않은 거 같아 아차~ 싶어서 적어도 같은 방식으로 이런 걸 또 제공하기는 어렵겠구나 싶었는데 말이지요.. 

## 1. 질문의 형식에 관해서 .. 

- 붙이자마자 교무실로 뛰어와서 저한테 직접 항의하고 서운함을 표시했으면 좋았을 거 같아요. 이렇게 익명으로 올리는 건 기본적으로 교사가 이런 문제제기에 부당한 손해로 되돌려줄 여지가 있다고 생각하는 걸 전제하는데 ... 왜 얼굴 보면서 학교에서 얘기해줄 수는 없었을까 저도 속이 상하네요. 
- 그래두 익명으로라도 문제제기하고 얘기하고 하는 건 좋은 거니깐... 이 사이트가 익명으로 수업에 관해 어떤 것도 의견 나눔할 수 있는 공간으로 여겼다면 본인 또한 문제제기의 방식에 있어서 학교와 교사를 익명처리했어야 해요. 교사 3명의 이름을 실명으로 월드와이드웹에 게시하면서 공격하는 건 일방적이고 부당해 보입니다. 

## 2. 질문에 대한 답변

> 1. 누구를 위한 예상 등급컷 자료입니까?

-- 응시한 학생들 중에 성적 사정이 끝나기 전에 등급컷이 궁금하다고 한 학생이 있어서 미리 계산해서 주면 어떨까 해서 게시해 보았어요. 

 
> 4등급 컷까지는 나와있지만 5,6,7,8,9등급 컷이 안 나와있는데, 5,6,7,8,9등급을 받을 애들은 자기 성적에 관심이 없다고 누가 그럽니까? 아니면 혹시 "헐 8등급컷이 7점이야 와 못하는 애들 많다" 라고 성적 잘 받은 애들이 떠들고 옆에 7점 받은 애가 상처받는 일을 피하려고 표시를 안 하신 건가요?

-- 후자에요. 
-- 제가 이 질문을 받고, "공부 못 하는 아이가 성적이 안 좋아서 열받아서 이렇게 문제제기하나보다"라고 생각하면 안 되겠지요? 저의 의도를 "4등급 이후 학생들은 없는 사람 취급하는구나"라고 오해하지 말아주세요. 
-- 우리 학교는 수강자가 적기 때문에 시험이 끝나고 채점을 해도 특히 상위권의 컷을 예측하기가 참 어려운데 이런 걸 미리 제공하면 이번 시험의 난이도나 본인의 공부한 결과를 평가할 때 도움이 되려나 싶어서 게시했을 뿐이에요. 뭐... 제가 이렇게 얘기해도 안 믿으실 수도 있지만..


 
> 1. 반별 1등의 점수가 나와있는데, 반마다 분위기는 다르겠지만... 애들이 성적에 얼마나 민감하고 서로의 성적에 궁금해하는건 뻔하게 아실 거라고 생각하는데... 8반에 만점자가 한 명 있어! 그러면 그게 누구인지 뻔할 수도 있고 8반 애들끼리 누구야? 누구야? 할 수도 있는데... 이걸 굳이 공개해야 될까요??

-- 이건 제 잘못인 거 같아요. 절대 성적만으로 누구인지를 유추하고, 평가하고, 1등 학생이 다 맞았을까 하나 틀렸을까를 앞에서 또는 뒤에서 서로 이야기하게 되는 분위기가 생길 수 있다는 걸 예상하지 못했어요. 속상하거나 본의 아니게 개인의 성취도를 공개 당한 친구들에게 상과하고 싶어요. ㅠ 
-- 여러분이 성적에 예민하다는 건 저도 잘 알고 있지만, 정말 오해하지 말고 들어주면 좋겠는데 우리가 성적에 관해 쉬쉬하는 분위기가 정말 좋기만 하다고 생각하지는 않아요. 이것은 성적을 나의 성장으로 받아들이지 못하고, 내가 스케이트보드를 탈 수 있게 되었는가의 관점이 아니라... 어쨌든 쟤보다는 내가 잘 타는가 등등에 관심이 더 많은 우리의 상대평가 풍토 때문이에요. 저는 성적은 그냥 성적일 뿐이라고 생각해요. 이 과목의 최고점이 공개되었을 때 그것을 "얘 누구야?" "야 우리반 못한다고 지금 까는 거지?"라고 생각하는 건 언제부터 우리에게 생긴 습관인가요? 이 정도의 난이도로 출제한 시험을 내가 보았는데 만점을 받은 친구가 우리반에 있구나, 아이들이 참 잘 하는구나. 라고 생각할 수 있지 않을까.. 라고 순진하게 생각했지요.. 우리는 왜 모의고사를 보고 전국 1등이 어느 학교에 다니는지 찾아보지 않으면서 늘 내신 공부할 때는 그게 누군지, 그게 몇 반인지 궁금해하는 걸까요? 이건 일반적인 걸까요, 아니면 문화일까요? 최고 학생을 공개한 게 아니라 성적 분포의 최고 성취 수준을 공개한 것인데 이것이 개인정보가 아니라 학습과 관련된 그냥 숫자로 된 정보로 읽힐 수는 없을까요? 왜 그런 걸 공개하면 아주 내밀하고 사적인 정보를 공개했다고 생각할까요? 그런 걸 공개하는 선생님은 통계정보를 준 건데, 왜 아이들은 1등 학생을 예뻐하거나 못하는 애들을 힘들게 하려는 의도가 있다고 읽을까요? 중요한 건 나의 점수와, 그것과 비교할 전체의 어떤 통계일 뿐이고, 모두 자신의 위치에서 성장하기를 원해요.
-- 그러나 .. 결과적으로 이것이 안 좋은 현상으로 드러나게 되어... 아마도 앞으로는 못할 거 같아요. 저도 여러분이 서로 눈치를 주고 받으며 속상해하는 건 싫거든요. 





> 개인차는 있겠지만 제가 만약 전교 1등을 한 학생이었다면 소속 반까지 드러나는 이런 게시물이 상당히 불편했을 것 같습니다.
> 

-- 그랬을 수 있을 거 같아요. 위에도 적었지만 제가 생각이 짧았던 부분이 있어요. 


> 1. 반별 평균을 공개하는게 자극이 될 수도 있지만... 어차피 영어과가 넘사벽인데 우리는 포기하자 가 될 가능성도 있을 것 같아요. (물론 영어과 핑계로 공부 안 하다가 평균 차이 얼마 안 나는거 보고 '넘사벽 같은건 없다, 공부 열심히 하자' 생각하는 경우도 있겠지만) 6반 애들이 기분 나빠할 수도 있을 것 같은데..

-- 어차피 영어과가 넘사벽 ... 이런 생각 너무 한심해요. 영어과는 없어요. 한 명 한 명이 있고, 그리고 내가 있을 뿐이에요. "우리"가 어디 있어요? 더 잘 하면 더더 잘 하는 집단과 타인은 늘 있어요. 그래서 포기하고 좌절하면 우울의 순환에 빠지는 거에요. 엊그제 (성적이 그렇게 좋지는 않은) 어떤 친구가 수학 문제 풀다가 안 풀리면 막 화가 난다고 했는데 그 말 들으니 기분이 엄청 좋더라고요. 이게 진짜 중요한 겁니다. 어차피 쟤네가 넘사벽인데 뭐라고 생각하지 말고,,, 내가 마주한 한 문제 앞에서 너무 힘들어서 화가나는 그 기분.. 그래서 풀고 나면 속시원한 그 기분.. 그런 내적 동기에 집중했으면 좋겠어요.
-- 반별 평균은 그래도 질문한 문제제기 내용처럼 부작용이 많은 통계 같아요. 근데 사실 외국인전형 준비하는 친구도 있고 다들 꿈도 다르고 다 다른 건데 평균만 보면서 와 우리는 영어과인데 6반 애들은 진짜 못한다 .. 이런 생각하는 친구야말로 정말 한심한 것이죠. 
-- 여튼... 위에도 적었지만 반별로 쓰는 거 이제 못할 거 같지요? ㅠ ㅠ 저는 6반 애들도 영어과 애들도 모두 참 이쁘고 좋은데 ... 절대 비교하면서 애들 자극하려고 쓴 거 아니에요. 엑셀로 그냥 긁어서 생각없이 만들었어요 ... 


> 2. 영어과만 선택형, 서술형이 표시되지 않은건 채점이 덜 끝나서 그랬던 건가요, 아니면 특별한 이유가 있나요?

-- 그건 제가 권한이 막혀있어서 통계 자료를 사전에 확보할 수가 없어서 그랬어요. 



> 3. 다음 날이 되자 잠잠해졌지만 화요일에 종례 끝나고 나서 다들 이걸 왜 붙이신건지 궁금해했어요. "내신 끝났는데 또 경쟁시키려는거야 뭐야" 라는 얘기도 나오고....

-- 그냥 애들에게 좀 전해주세요. 쌤이 멍청해서 애들 무슨 생각하는지 예상을 못했던 거 같다.. 
-- 그리고 열받아서 질문한 질문자님, 괜찮으면 교무실 와서 악수합시다. 

> 
> 저는 개인적으로 전교생 종합/선택형/서술형 평균, 등급컷을 공개하신거, 어쩌면 영역별 전교 최고점수까지 공개됐어도 그러려니 했을 것 같은데 이렇게까지 구체적인 데이터를 공개하시는 취지를 잘 모르겠고 약간 불편합니다.

-- 전교 기준 정보를 미리 제공하는 것은 유익할지 좀 더 생각해보고 담에는 더 미리 계획하고 신중하게 진행할게요. 이번에 사전 공개된 데이터가 불필요하게 세부적이고 많은 정보를 제공했다는 지적 고맙습니다. 그냥 화 내고 돌아서는 친구도 많았을텐데 이렇게 글로 문제제기 해주어 또한 고마워요.

**Comment by seoulrain** [comment]
아 맞다, 일단 실명이 있는 사진 자료를 제가 삭제할게요. 동의해줄 거라고 믿어요.
