### ISSUE TITLE
영독 1강 EX11

### ISSUE THREAD

**Issue by beenyan02** [seoulrain/studyhacks#221]
본문에서 inner sensation of pain을 consciousness라고 봐야하는건가요?
만약 맞다면 그 다음 문장(우리 자신의 경우에서조차도 통증은 흔히 팔다리가 잘린 후에야 비로소 느껴진다)과 어떻게 연결되는건가요?

**Comment by user4798** [comment]
질문 유의사항 필독. 
질문만 보고 충분히 질문의 의도를 이해할 수 있도록 본문을 제시해야.
