### ISSUE TITLE
영어 test2 13

### ISSUE THREAD

**Issue by sebinHwang** [seoulrain/studyhacks#222]
shades of gray에 반대되는 예시로 zero-sum game이 제시됐는데 제가 이해한게 맞는지 질문하려 합니다 
제로섬 게임이 한 사람이 얻은 만큼 다른 사람이 손실을 입는 걸 의미하는 걸로 알고 있는데요,  바둑돌을 예시로 들었을 때 10개 중 검은 바둑돌이 7개를 차지하면 흰 바둑돌의 자리 7개를 뺏기는 것이어서 zero-sum game이 되는건가요?

**Comment by user4798** [comment]
제로섬의 개념은 인터넷 검색으로 알 수 있습니다. 

10개의 바둑돌 놓을 자리가 바둑판에 있을 때 
검은 바둑돌 7개는 곧 흰 바둑돌 3을 즉시 의미합니다. 

검은 바둑돌 7개가 흰 바둑돌 7개의 자리를 빼앗은 효과일까요?
그렇습니다!
