### ISSUE TITLE
1강 2번

### ISSUE THREAD

**Issue by CH1718** [seoulrain/studyhacks#224]
5번째 줄에 if절 문장이 무슨 말인지 잘 이해가 안가요. 전후 개념도가 뭘 의미하는지 잘 모르겠어요

**Comment by user4798** [comment]
질문 유의사항 필독. 

선생님이 즉시 답할 수 있도록 풍부하게 본문의 내용을 제공하세요. 
갑자기 6번째 줄에 if 그거 머에요? NONO~
