### ISSUE TITLE
영어 TEST 1강 14번 

### ISSUE THREAD

**Issue by sebinHwang** [seoulrain/studyhacks#225]
지문 전체에서 exercise에 대해 얘기하고 있는데 첫 줄에 desk setups 얘기가 왜 나왔는지 잘 모르겠어요 그리고 desk setup에 integrating exercise를 한다는게 잘 안 와 닿아요!

**Comment by user4798** [comment]
텍스트 안 보이네요. 
질문유의사항 꼭 읽으세요. 

갑자기 그거 머에요~ 라고 질문하면 답하기 힘들어요. 모두 타이핑할 필요는 없지만 자신이 어떤 부분을 질문하는지 참고할 내용을 충분히 써주어야 해요.

**Comment by sebinHwang** [comment]
> 지문 전체에서 exercise에 대해 얘기하고 있는데 첫 줄에 desk setups 얘기가 왜 나왔는지 잘 모르겠어요 그리고 desk setup에 integrating exercise를 한다는게 잘 안 와 닿아요!

텍스트 다시 올려요! 
Office workers can sometimes choose their own desk setups, integrating exercise on an individual basis.

**Comment by user4798** [comment]
뭐 그건 자세히는 안 나왔으니 알 수 없고, 
책상 세팅을 달리 해서 따로 헬스클럽에 가지 않고 운동이 되도록 한다는 뜻이겠죠? 

책상 세팅이 운동이 되도록 하는 제품은 이미 많이 있습니다. 

https://www.google.co.kr/search?q=desk+setup+exercise&sxsrf=ALeKk01zYLrYo8JP9ksIqfxe1UnkLnN0_g:1589962140854&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjRoPLE_sHpAhVtw4sBHZW5AxcQ_AUoAXoECAwQAw&biw=2133&bih=1041
