### ISSUE TITLE
영어 test1강 14번

### ISSUE THREAD

**Issue by sebinHwang** [seoulrain/studyhacks#226]
5번째 줄까지 직원들의 운동을 회사차원에서 들이는것의 장점을 얘기하고있고 그 근거로 질병감소를 들었잖아요,
5번째 줄에선 지적 능력또한 향상시켜준다인데 앞의 두 내용이 But으로 묶인게 이상해서 질문합니다! 
혹시 뒤에 also가 와서 but이 온걸까요? Moreover같은게 더 자연스럽지않나해서 질문했습니다

**Comment by user4798** [comment]
ㅜㅜ 본문의 텍스트를 제공해야 답을 할 수 있어요.

**Comment by sebinHwang** [comment]
> 5번째 줄까지 직원들의 운동을 회사차원에서 들이는것의 장점을 얘기하고있고 그 근거로 질병감소를 들었잖아요,
> 5번째 줄에선 지적 능력또한 향상시켜준다인데 앞의 두 내용이 But으로 묶인게 이상해서 질문합니다!
> 혹시 뒤에 also가 와서 but이 온걸까요? Moreover같은게 더 자연스럽지않나해서 질문했습니다

텍스트 첨부해서 다시 올려요!
There's no question that halving someone's lifetime risk of a debilitating stroke or Alzheimer's disease is a wonderfully humanitarian thing to do. But exercise also could boost the collective brain power of an organization.

**Comment by user4798** [comment]
But .. 다음에 꼭 논리적으로 반대 주장이 연결될 필요는 없습니다. 

롱맨 사전 : "used to connect two statements or phrases when the second one adds something different" 

즉, 앞의 내용과 꽤 달라 보이는 주장을 새로 소개할 때도 씁니다. 
달라보인다는 건 독자 입장에서 그러리라 생각이 되면 필자가 쓰는 것이죠. 

예문) It's an old car, but it's very reliable.
차가 오래 됐지만, (그리고 독자인 너는 그래서 차가 똥차라고 생각할 수도 있겠으나), 차가 괜찮다. 

맥밀란 : used for introducing a different idea used for joining two ideas or statements when the second one is different from the first one, or seems surprising after the first one:

맥밀란에서는 surprising fact를 제시한다고 필자가 생각하면...  독자 입장에서 잘 몰랐고 놀라운 사실을 소개하고 싶을 때(surprising), but을 붙여 이야기할 수 있습니다. 


본문에서는 ... brain power 를 운동이 증진시킨다는 점을 독자가 예상하기는 힘들었을 것으로 필자가 생각하기에, A는 너도 알고 있는 효과이겠지. 그런데!(But) / B에도 운동이 효과가 있다는 것이야!
