### ISSUE TITLE
영어 TEST 01강 6번

### ISSUE THREAD

**Issue by EEE-A** [seoulrain/studyhacks#229]
마지막 두문장
In short, if athletes define themselves as winners, they are more likely to win.
By the same token, if athletes define themselves as losers, they will very likely lose.
에서 뒷문장에 By the same token이 ‘마찬가지로’라는 뜻인데 왜 앞문장이랑 반대되는 내용이 나오는건가요?

**Comment by user4798** [comment]
내용과 주장이 같다는 맥락이 아니라, 
그 작용 방식이 같다는 것입니다. 

너가 한 대 맞으면 아프지?
마찬가지로, 내가 맞으면 기분이 어떨 거 같아? 

> **by the same token** 
> for the same reasons - used when you want to say that something else is also true, especially something very different or surprising
> 같은 이유에서, 마찬가지로 -- 다른 상황에서도 똑같이 적용되는 이야기를 꺼낼 때 자주 쓴다. 특히 뒤에 나오는 이야기가 아주 놀랍거나 새로운 이야기일 때. 
> 예문) The penalty for failure will be high. But, by the same token, the rewards for success will be great.
> 실패하면 손해가 클 거야. 그러나, 마찬가지로(똑같은 이유 때문에), 성공하면 보상이 크다구. 


In short, if athletes define themselves as winners, they are more likely to win.
By the same token, if athletes define themselves as losers, they will very likely lose.

여기서는 승자로 정의하면 이기는 것과 같은 이유 = 어떻게 정의하느냐가 결과에 영향을 미친다는 점이 같죠? -- 따라서 같은 이유로, 
실패자로 스스로를 정의하면, 결과는 패배입니다.
