### ISSUE TITLE
영독 3강 11번

### ISSUE THREAD

**Issue by k2oo2** [seoulrain/studyhacks#230]
본문 내용에서 정서가 개인별로 유사성을 가지고 있지만 그럼에도 개인적인 차이가 있다고 언급하는데 그러면 두번째 문장에서 감정이 개인적이고 교육될 수 있다는 사실이 감정에 있어서 개별적 차이를 불러일으키는 원인으로 보는거고 첫번째 줄에 the fact that emotions are unlearned, automated, and set by the genome 이 정서가 개인들 사이에 유사성을 보이는 이유인거죠?

**Comment by user4798** [comment]
넵
