### ISSUE TITLE
3강 3번

### ISSUE THREAD

**Issue by wow773** [seoulrain/studyhacks#231]
In other words 로 시작하는 문장에서 they may simply reflect flexibility in a response that is quite adaptive in the environments ordinarily encountered by the species라는 문장에서 상당히 적응적인 반응의 유연성이라고 flexibility in a response가 해석 되는데 그게 무엇에 대한 적응적인 반응의 유연성인지, 왜 유연성이라는 단어를 갑자기 쓴건지 이해가 안갑니당 ㅠㅠ

**Comment by user4798** [comment]
adaptive 하지 않다고 볼 수 없고 flexible 하다고 봐야한다는 것이겠죠. 

normal environtments 에서는 deviant responses are nonadaptive 하지만,
abnormal environtments 에서는 deviant responses 는 notadaptive  한 게 아니라, flexibility를 지닌 것으로 볼 수 있다는 것. 

Devaint responses in abnormal environments are not nonadaptive. 
Deviant responses shows flexibility in a normal response (통상적인 환경에서 적응적이라고 보였던 어떤 반응). 

환경이 변했을 때 반응이 변한 것은 적응 실패가 아니라
환경이 변하기 전 통상적 환경에서 적응적이었던 반응이 유연성을 발휘한 것이다. 

ㅇㅋ?
