### ISSUE TITLE
영어 테스트1,2 질문

### ISSUE THREAD

**Issue by qkrwldls02** [seoulrain/studyhacks#232]
1. 테스트 1 4번
마지막 문장에 최고의 투수인 Robin Roberts를 막기 위해서 "make me his catcher" 하면 된다고 나오고 이것의 함축 의미가 'without a good catcher, he couldn't be the best pitcher' 이라고 하는데 그러면 'I'는 스스로가 좋은 포수라고 생각하는 건가요? 

2. 테스트1 17번
이 지문에서 세 번째 문장에 나오는 사람들이 19세기 colonial conflict에 참가한 'novel reason' 이 'to make claims to membership in the home nation' 이라고 이해하면 되나요?

3. 테스트2 7번
네 번째 문장에 problems of image and social control이 어떤 것들을 의미하는지 잘 모르겠어요.

**Comment by user4798** [comment]
1. 아니지요... 
그 앞에 'how to stop Robin'이라고 했으니까요. 
현재의 합이 맞는 좋은 포수 덕분에 Robin이 unstoppable 한 것이고요. 

2. 그렇죠

3. 한 도시의 이미지 문제와 사회적 통제=특정 계층에 대한 통제를 의미합니다. 
demarcated zone이 없다면 
관광객들에게 어떤 도시의 이미지가 안 좋게 보이거나, 
우리 도시에서 보여주고 싶지 않은 사람들을 통제해서 관광객과 만나지 않도록 하는 통제가 힘들겠지만

defended zone을 처음부터 구성하면 거기까지 가는 길 말고는 이런 통제 문제나 이미지 문제는 해결되는 것이지요.
