### ISSUE TITLE
영어독해연습 1강 9번

### ISSUE THREAD

**Issue by brillerfleur** [seoulrain/studyhacks#233]
지문에서 나오는 fine feelings, intellectual achievements, value systems, 그리고 stories (we have traditionally told ourselves about why we hold them)는 회의론자들이 무가치하다 판단하여 버려야 할 낡은 형이상학적 개념에 포함되나요?

**Comment by user4798** [comment]
fine feelings와 지적 성취에 대해서 회의론자들이 그것을 부정하는 것은 아니죠. 
고등한 지능과 감정의 원인으로 지목하는 것들이 무엇이냐는 질문 앞에 
그것이 the supernatural 한 것으로부터 생겨난 게 아니라고 해서

지금 우리의 지능과 감정이 저능한 것으로 떨어지거나 소중하지 않게 되는 게 아니라는 것입니다. 

본문에서 정교한 지적 생명체인 우리 자신에 대해 회의론자들이 거부하라고 주문한다고 독해해서는 안 됩니다.
