### ISSUE TITLE
영어 test 2 #24,25 지문

### ISSUE THREAD

**Issue by brillerfleur** [seoulrain/studyhacks#234]
The effects of authority depend on the motives of those exercising it.
지문의 마지막 문장의 해석을 권위의 효과는 it(=권위)를 행사하는 자들(=those=formal leaders)의 동기에 따른다.  이라고 보는 것이 맞나요?

**Comment by user4798** [comment]
The effects of authority depend NOT on its nature, BUT on the people who exercise it. 

권위를 휘둘러 긍정적인 영향과 결과가 생기느냐하는 문제는
권위 자체가 선하냐 좋은 것이냐와는 상관이 없습니다. 
권위는 자원의 교환을 촉진하는 정도로 도울 뿐이고, 
권위로 인해서 많은 사람이 이익을 얻느냐 하는 문제는 결국  the motives (the reason that makes the people with power do something) 이 좌우합니다.
