### ISSUE TITLE
영독 1강 9번

### ISSUE THREAD

**Issue by sebinHwang** [seoulrain/studyhacks#235]
밑에 비슷한 질문을 한 친구가 있어서 그 질문에 덧붙여서 질문하고 싶은데요,
앞에서 comforting beliefs 없이도 살 수 있다는 얘기가 나온 뒤
 **So what if our fine feelings and intellectual achievements are just the stretching and turning of so many springs or wheels, or our value systems are mirrored by those of chimpanzees and baboons.** Our feelings are no less fine, and our values no less precious because the stories we have traditionally told ourselves about why we hold them turn out to be fables.

볼드체 문장 때문에 헷갈려서 질문합니다! 
처음 이해한 내용 : 사람들은 comforting beliefs를 믿어서 fine feelings & intellctual achievements를 얻음 -> (그런데 comforting beliefs는 없어도 되는 것이므로) fine feelings & intellectual achievements 가 단순히 springs or wheels일지라도 (=comforting beliefs가 없는 구조) fine feelings & achievements를 가지를 수 있다. 
라고 생각해서 fine feelings & intellectual achievements가 comforting beliefs로부터 얻는 것.이라고 생각했었는데

그래서 결론은, fine feelings and intellectual achievements가 comforting beliefs로 부터 얻는 대상이 아니라 stretching and turning하는 존재 (없어도 되는데 사람들이 comforting beliefs로 믿고 의지하는 것)가 되는 것인지 궁금합니다.

텍스트로 질문하려니까 구구절절 얘기하게 되네요ㅠㅠ

**Comment by user4798** [comment]
1. 사람들이 comforting belief 덕분에 fine feelings 를 얻는 게 아니라
fine feelings 의 원인이 "하나님이 너를 그렇게 예쁘게 만들어주신 거야, 착하게 살라고" 등등과 같이 
동화와 같은 supernatural 한 원인 때문이라고 생각하는 믿음이 과학적이지 않은 comforting belief  라는 겁니다. 

2. 회의론자들은 그런 comforting belief 는 과학적이지 않고, 알 수 없고, 버려야 한다고 생각하겠죠. 

3. 증거에 기반해서 우리의 fine feelings  의 원인을 설명하려는 과학자들은 오히려 우리가 유전자와 피와 신경다발 등등으로 움직인다고 설명하는 사람이 많을 거에요. 
"우리는 유전자 묶음이다! 스프링 조립품이다!"  "신이 우리는 만들어줬다는 동화는 틀렸다!"

4. 이런 회의론자들의 주장을 공격하는 많은 사람들은 그들의 이런 주장이 인간의 존엄성을 해친다고 말합니다. 인간이 그저 유전자 덩어리이고 동물과 다를 바가 없다면 우리는 너무나 초라하지 않은가?

5. 본문은 이에 대해,
이런 comforting belief  를 버릴지라도 여전히 우리의 현 상태는 지적으로 고등하고 감정적으로 정교한 생물이라는 사실은 변하지 않는다는 것입니다. 따라서 우울해할 필요가 없다는 것이죠.
