### ISSUE TITLE
영어 test 1 17번

### ISSUE THREAD

**Issue by sebinHwang** [seoulrain/studyhacks#237]
Popular participation in conflict in the nineteenth century cannot be understood without
examining the role of empire. Individuals had always gone to the colonies for profit or to
settle. But individuals also participated in nineteenth-century imperial campaigns for a
**novel reason.** 

novel reason이 
superfluous 한 자본과 사람을 수출하는 것 & 구성원으로서 인정받기 위해
를 의미하는 것 맞나요?

**Comment by user4798** [comment]
superfluous 한 자본과 사람을 수출하는 것

과 

 구성원으로서 인정받기

의 관계를 잘 독해하도록 하세요.
