### ISSUE TITLE
추가자료 1-3회 질문 답

### ISSUE THREAD

**Issue by kyla333** [seoulrain/studyhacks#67]
추가자료 1-3회 질문정리 프린트에서 1회 1번의 답이 
용기와 같은 추상적인 단어를 모르는 사람은 없지만 막상 개념을 말하려면 시간이 걸린다는 것을 알려주려고  가 맞나요?

7. the basis for our analysis 랑 objects of analysis 의 차이가 0000 맞나요?
답이 문화차이 맞나요?

Quite simply, then, in order to study cultural matters, many sociologists believe one has to reject the terms 'art', 'artwork' and 'artist' as the basis for our analysis. Instead, these terms become important objects of analysis themselves. 에서 our analysis가 어떤 내용을 가리키는 건지 모르겠어요. 

7. 선지 5번의 근거를 본문 어디에서 찾아야 되는 건가요?
This is a category that is too limited and context-specific to encompass all the different cultural products that people in different societies make and use. 가 근거가 되는 거 맞나요?

같은 지문에서 the study of what our society calls 'art' can only really progress if we drop the highly specific and ideologically loaded terminology of ~ 에서 art 라는 개념이 너무 특정한 개념에 제한되어 있고 (본문 뒤에 내용도 참고하면) 이 개념을 사용하는 것이 특정 집단에게 이익이 되기 때문에 art 말고 모두가 쓸 수 있는 cultural products를 쓰자는 거 아닌가요? 근데 These cultural products should be regarded as being made by certain types of cultural producer. and as being used by particular groups of people in particular ways in specific social contexts. 를 보면 cultural products도 특정한 개념이라고 말하고 있지 않아요? 그러면 art, cultural product 의 공통점은 둘 다 specific 하다는 걸로 들 수 있나요?

2회
1. adjusting to another person's mental orientation 이라는 게 결국 0000이라고 요약해 보았는데 맞나요?
다른 사람이 어떻게 느끼는지 생각해 보는 것 아닌가요? 맞약 맞다면 4단어의 답은 무엇인가요?

2. reflect the underlying conditions 에서 그 환경 조건이란 000인가요?
답이 뭐예요... 모르겠어요 저는 예상치 못 한 상황이라고 생각했어요...

4. 음악 얘기는 왜 한 건가요?
규제된 학습의 필요성을 이해시키려고 가 맞나요?

4.저자는 b부분에서 free trial and error 를 통해서도 결국은 조금 배울 수 있다고 필요성을 인정하는 입장이죠?

추가자료4회

401-2 위험 포트폴리오란?
위험 포트폴리오가 뭔지 당최!!! 모르겠어요.

406 It was for this reason that Gans referred to them as urban villagers. 에서 Gans가 그렇게 말한 이유가 도시에 살고는 있지만 시골 사람들처럼 국한된 네트워크, 유대관계를 가지고 있어서 인가요?

407-8
If you are three hours behind the time in Greenwich, you are 45 degrees west. 에서 매 시간마다 태양은 15도 씩 움직인다고 했으니까 15*3=45도 알겠는데 west는 도대체 어떻게 알 수 있을 까요?

**Comment by seoulrain** [comment]
전체적으로 어디에 있는 어디에 해당하는 질문을 하고 있는지 알기 어려워요. 
또한 질문은 끊어서 올려주면 좋겠어요. 


## 1. 
> 추가자료 1-3회 질문정리 프린트에서 1회 1번의 답이-
> 용기와 같은 추상적인 단어를 모르는 사람은 없지만 막상 개념을 말하려면 시간이 걸린다는 것을 알려주려고 가 맞나요?

프린트 1번의 답이 00인가요? 와 같이 질문하지 말아주세요. 
모든 질문은 질문의 내용이 되는 본문을 포함해야 합니다. 
제가 어디 말하는 거지? 하고 책을 꺼내지 않아도 답변할 수 있게 충분한 내용을 더해주세요. 


## 2. 
> the basis for our analysis 랑 objects of analysis 의 차이가 0000 맞나요?
> 답이 문화차이 맞나요?

모든 질문은 질문의 내용이 되는 본문을 포함해야 합니다. 
제가 어디 말하는 거지? 하고 책을 꺼내지 않아도 답변할 수 있게 충분한 내용을 더해주세요. 


## 3. 
> Quite simply, then, in order to study cultural matters, many sociologists believe one has to reject the terms 'art', 'artwork' and 'artist' as the basis for our analysis. Instead, these terms become important objects of analysis themselves. 에서 our analysis가 어떤 내용을 가리키는 건지 모르겠어요.

우리가 cultural matters를 연구study/분석analyze 할 때의 기초를 말하는 것이죠. the basis for our studying cultural matters 입니다. 


## 4. 
> 선지 5번의 근거를 본문 어디에서 찾아야 되는 건가요?
> This is a category that is too limited and context-specific to encompass all the different cultural products that people in different societies make and use. 가 근거가 되는 거 맞나요?

선지5번이 뭔데요? 
제가 프린트를 계속 휴대하고 다니는 게 아니에요. 
이하 질문과 그 참조 내용이 이 글 안에 없는 질문은 스킵합니다. 


## 5. 
> 같은 지문에서 the study of what our society calls 'art' can only really progress if we drop the highly specific and ideologically loaded terminology of ~ 에서 art 라는 개념이 너무 특정한 개념에 제한되어 있고 (본문 뒤에 내용도 참고하면) 이 개념을 사용하는 것이 특정 집단에게 이익이 되기 때문에 art 말고 모두가 쓸 수 있는 cultural products를 쓰자는 거 아닌가요? 근데 These cultural products should be regarded as being made by certain types of cultural producer. and as being used by particular groups of people in particular ways in specific social contexts. 를 보면 cultural products도 특정한 개념이라고 말하고 있지 않아요? 그러면 art, cultural product 의 공통점은 둘 다 specific 하다는 걸로 들 수 있나요?

1. 특정 집단에게 이익이 된다는 말은 없습니다. 
2. 모든 문화적 산물은 특정 집단에 의해 만들어지고, 특정한 사회적 맥락을 반영하는 것으로 취급되어야should be regarded 한다는 것은 현재 그렇게 취급되지 않고 있어서 유감이라는 어조이지요. 왜? art 라는 말을 사용하면서 매우 특정적이고 사상적으로 기울어져 있기 때문이다...   모두가 저마다의 맥락이 있는 것인데, '예술'이라고 하면 그 중의 일부 특정한 맥락만을 가리키게 되는 게 문제이다 그런 관찰이지요. 




"답이 뭐지?" 게시판에 답이 뭐냐고 물어보면 적어주겠지~ 
라고 생각하고 프린트 질문만 복사해서 올리지 마세요. 


아래 형식을 지키세요. 

게시글 제목 : 00회 00번
게시글 내용: 
00글에 이런 본문이 있습니다. 
asdfasd asdf asdf asd
asdfas
fasdfasdfafssdf asdfasdf

여기서 'xxx'가 000의 근거가 되냐는 질문이 프린트에 있는데 그 위의 000가 이유라고 저는 생각했어요. 
왜냐하면 0000가 0000인데 000이니까요. 
하지만 000가 000이니까 ???도 가능하지 않을까 생각이 되고 친구랑 서로 의견이 엇갈리는데요
제 생각에는 000이니까 000일리는 없는 거 같은데 맞습니까? 

적어도, 이렇게 질문을 어떻게 고민해보았고 **그 근거**는 나름 000때문이라고 생각했다는 내용을 포함시키십시오. 



------------ 이하 모두 스킵 -----------


## 2회
> adjusting to another person's mental orientation 이라는 게 결국 0000이라고 요약해 보았는데 맞나요?
> 다른 사람이 어떻게 느끼는지 생각해 보는 것 아닌가요? 맞약 맞다면 4단어의 답은 무엇인가요?

어디.. 뭐가? 

## 2회 어디??? 
reflect the underlying conditions 에서 그 환경 조건이란 000인가요?
답이 뭐예요... 모르겠어요 저는 예상치 못 한 상황이라고 생각했어요...

> 답을 니가 생각을 먼저 해보고 질문을 해라. 


## 2회 

> 음악 얘기는 왜 한 건가요?
> 규제된 학습의 필요성을 이해시키려고 가 맞나요?

그건 당연한데, 왜 음악 얘기부터 한 걸까? 


## 4.저자는 b부분에서 free trial and error 를 통해서도 결국은 조금 배울 수 있다고 필요성을 인정하는 입장이죠?

아니오. 



## 추가자료4회

## 401-2 위험 포트폴리오란?
위험 포트폴리오가 뭔지 당최!!! 모르겠어요.

> 본문의 내용입니다. 

406 It was for this reason that Gans referred to them as urban villagers. 에서 Gans가 그렇게 말한 이유가 도시에 살고는 있지만 시골 사람들처럼 국한된 네트워크, 유대관계를 가지고 있어서 인가요?

>> 네 


407-8
If you are three hours behind the time in Greenwich, you are 45 degrees west. 에서 매 시간마다 태양은 15도 씩 움직인다고 했으니까 15*3=45도 알겠는데 west는 도대체 어떻게 알 수 있을 까요?

>> 본문을 좀 더 주세요.
