### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by yejinshin01** [seoulrain/studyhacks#78]
102
 AI 지문에서 In the grandest irony of all, the greatest benefit of an everyday AI ~ is that AIs will help define humanity 여기서 어떤 점이 irony하다는 건지 생각해봤는데요, 
AI가 인간이 할 수 있는 것을 빼앗아가서  painful and sad하지만 그것( AI가 인간이 유일하게 할 수 있는게 무엇인지 고민하게 하는 것)이  가장 큰 AI 의 베네핏이라는게 irony 하다고 이해했는데 맞는건가요?
203
자기 소개할 때 자기가 하는 일로 소개하는 사람 얘기하는 지문인데요
추가프린트 질문 중 Psychologically, we become what we believe. 이런 말 왜 함? 이 질문에서 저는 답이: 앞에서는 criminal 한 건 아니지만 이라는 말을 했으니까 이것과 이어져서 죄는 아니지만(나쁜건아니지만)심리학적으로는 안 좋은 영향을 끼칠 수 있다라는 걸 말하려고 했다고 생각하는데 혹시 방향이 잘못되었나요? we become what we believe 의 의미에 초점을 둬야하나요?

**Comment by seoulrain** [comment]
102. 
물결 표시에 포함된 내용을 포함해서 대조해야하는데 안 보입니다. 
아이러니하게도, A가 아니라 오히려 B인 것이다. 
아이러니하게도, 원래 000을 하려고 만든 인공지능이 ... 물론 000도 하게 해준 건 맞는데, **거꾸로** 인간이란 무엇이냐고 묻고 있는 상황이다. 



203. 
질문에는 근거와 질문의 내용이 포함되어야 합니다. 
프린트에 000답이 ---가 맞아요?라고 질문하면 곤란해요.
