### ISSUE TITLE
질문

### ISSUE THREAD

**Issue by yejinshin01** [seoulrain/studyhacks#91]
106  reading classical texts 의 이점을 말하는 지문에서 마지막에 The academics said this meant the classics were more useful than self-help books. 에서 답지에는 self- help books가 자습서라고 나와있던데 자습서가 다른 외부 도움없이 독학할 수 있는 책이라고 생각해서 이 지문과 큰 관련이 있는 건지 잘모르겠는데 찾아봤더니 자기계발서라는 뜻도 있었는데 자기계발서를 읽으면서 자신의 인성이나, 자신의 가치관을 돌아볼 수있듯이 classics이 self reflection  을 도와주니까 ( 물론 more useful이긴 하지만)이러한 유사성 때문에 self help books라는게 쓰인건가요?
205 수은 지문
마지막에 Fish advisories have been issued for many lakes in the US ; these recommend limits on the number of times per month particular species of fish should be consumed. 이 문장이 나오는데, 이 advisories는 minamata disease를 예방하기 위해 발표되었다고 보면 되는건가요?   이 문장 전까지에서는 직/간접적인 discharging, emission 에 대한 기준이 필요하다고 말하고 있는데 왜 갑자기 맨 앞에서 나온 minamata disease 에 대한 advisories를 얘기하는 건지 잘 모르겠습니다.

**Comment by seoulrain** [comment]
> 106 reading classical texts 의 이점을 말하는 지문에서 마지막에 The academics said this meant the classics were more useful than self-help books. 에서 답지에는 self- help books가 자습서라고 나와있던데 자습서가 다른 외부 도움없이 독학할 수 있는 책이라고 생각해서 이 지문과 큰 관련이 있는 건지 잘모르겠는데 찾아봤더니 자기계발서라는 뜻도 있었는데 자기계발서를 읽으면서 자신의 인성이나, 자신의 가치관을 돌아볼 수있듯이 classics이 self reflection 을 도와주니까 ( 물론 more useful이긴 하지만)이러한 유사성 때문에 self help books라는게 쓰인건가요?

-- 자습서 어감이 이상하지요? 자기계발서로 읽는 게 더 적절해 보입니다. 

> 205 수은 지문 / Fish advisories have been issued for many lakes in the US ; these recommend limits on the number of times per month particular species of fish should be consumed. 이 문장이 나오는데, 이 advisories는 minamata disease를 예방하기 위해 발표되었다고 보면 되는건가요? 

-- 섭취 제한은 수은 축적을 방지하는 거니까 그렇다고 볼 수 있겠죠. 그러나 글에서 이 문장이 등장하는 위치가 ... 무슨 얘기 다음입니까? 이런 조치가 왜 일본과 떨어진 곳에서 발동 되었나요? 

> 이 문장 전까지에서는 직/간접적인 discharging, emission 에 대한 기준이 필요하다고 말하고 있는데 왜 갑자기 맨 앞에서 나온 minamata disease 에 대한 advisories를 얘기하는 건지 잘 모르겠습니다.

-- 본문의 주 요지가 산업 방출이 일부 지역에만 영향을 끼치지 않는다는 게 글의 핵심 내용 아닌가요? A 지역의 오염으로 인한 피해를 예방하기 위한 조치가 아주 멀리 떨어진 B에도 내려질 수 있는 이유를 설명하는 글인데 ~ 왜 저 멀리 호수에 이러한 advisories 를 내린 건지 궁금하다면 이 글을 처음부터 다시 읽어야~
