### ISSUE TITLE
10-7,8

### ISSUE THREAD

**Issue by PurpyThePolite** [seoulrain/studyhacks#92]
첫 문단의 "The change from a century before was enormous" 에서 the change 는 18세기에 청중들이 새 음악을 요구했고, 고대음악의 기준도 20세기와 달랐는데 20세기에는 청중들이 클래식을 기대하고, 고대 음악의 기준이 한 세대 전의 음악이 된 것이라고 생각하는데 이게 맞나요?

 그리고 한 세기 전에 변화가 일어났다는 것인가요 아니면 한 세기 전과 변화가 있다는 것인가요

**Comment by seoulrain** [comment]
a century before .. 는 ~를 기준으로 한 세기 전이니까 
그 앞에서 얘기한 turn of the twentieth century (20세기로 턴~할 때 쯤)보다도 100년 전에는 ~ 이라는 거죠. 

1800년 정도와 1900년 정도~를 비교하는 것이고 ... 
그 차이와 변화the change 가 엄청났다는 말입니다.
